In [1]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv('INC 5000 Companies 2019.csv')
df

,rank,profile,name,url,state,revenue,growth_%,industry,workers,previous_workers,founded,yrs_on_list,metro,city
0,1,https://www.inc.com/profile/freestar,Freestar,http://freestar.com,AZ,36.9 Million,36680.3882,Advertising & Marketing,40.0,5,2015,1,Phoenix,Phoenix
1,2,https://www.inc.com/profile/freightwise,FreightWise,http://freightwisellc.com,TN,33.6 Million,30547.9317,Logistics & Transportation,39.0,8,2015,1,Nashville,Brentwood
2,3,https://www.inc.com/profile/ceces-veggie,Cece's Veggie Co.,http://cecesveggieco.com,TX,24.9 Million,23880.4852,Food & Beverage,190.0,10,2015,1,Austin,Austin
3,4,https://www.inc.com/profile/ladyboss,LadyBoss,http://ladyboss.com,NM,32.4 Million,21849.8925,Consumer Products & Services,57.0,2,2014,1,NaN,Albuquerque
4,5,https://www.inc.com/profile/perpay,Perpay,http://perpay.com,PA,22.5 Million,18166.4070,Retail,25.0,6,2014,1,Philadelphia,Philadelphia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5007,4996,https://www.inc.com/profile/village-plumbing-air,Village Plumbing & Air,villageplumbing.com,TX,15.8 Million,52.2377,Consumer Products & Services,88.0,62,1946,3,Houston,Houston
5008,4997,https://www.inc.com/profile/real-restoration-g...,Real Restoration Group,realrestoration.com,IL,11.6 Million,52.2127,Construction,380.0,220,2011,1,Chicago,Chicago
5009,4998,https://www.inc.com/profile/naval-systems,Naval Systems,n-s-i.us,MD,29.7 Million,52.2037,Government Services,187.0,127,2004,1,NaN,LEXINGTON PARK
5010,4999,https://www.inc.com/profile/hnm-systems,HNM Systems,hnmsystems.com,CA,8.8 Million,52.1919,Telecommunications,132.0,47,2011,1,San Diego,Solana Beach
5011,5000,https://www.inc.com/profile/vivayic,Vivayic,vivayic.com,NE,4.5 Million,52.1691,Business Products & Services,27.0,22,2006,4,NaN,Lincoln

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5012 entries, 0 to 5011
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   rank              5012 non-null   int64
 1   profile           5012 non-null   object
 2   name              5012 non-null   object
 3   url               5012 non-null   object
 4   state             5012 non-null   object
 5   revenue           5012 non-null   object
 6   growth_%          5012 non-null   float64
 7   industry          5012 non-null   object
 8   workers           5011 non-null   float64
 9   previous_workers  5012 non-null   int64
 10  founded           5012 non-null   int64
 11  yrs_on_list       5012 non-null   int64
 12  metro             4199 non-null   object
 13  city              5012 non-null   object
dtypes: float64(2), int64(4), object(8)
memory usage: 548.3+ KB

In [40]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(df['revenue'])

0        36.9 Million
1        33.6 Million
2        24.9 Million
3        32.4 Million
4        22.5 Million
5       271.8 Million
6        20.5 Million
7        23.3 Million
8       225.9 Million
9        21.4 Million
10       13.9 Million
11       30.3 Million
12       19.1 Million
13       19.1 Million
14       17.3 Million
15       10.7 Million
16      105.8 Million
17         19 Million
18       24.4 Million
19        9.6 Million
20       10.2 Million
21       11.9 Million
22       13.8 Million
23       10.5 Million
24        8.9 Million
25      128.2 Million
26       15.8 Million
27        7.8 Million
28       11.8 Million
29        156 Million
30       20.4 Million
31       10.2 Million
32        7.2 Million
33       20.8 Million
34      162.6 Million
35       48.9 Million
36         24 Million
37       17.5 Million
38       45.2 Million
39       15.2 Million
40        8.3 Million
41        6.4 Million
42          7 Million
43        8.8 Million
44        6.2 Million
45       16.9 Million
46        6.3 Million
47        9.8 Million
48        7.1 Million
49       48.5 Million
50         25 Million
51       42.5 Million
52       23.9 Million
53       58.8 Million
54        5.1 Million
55          8 Million
56        7.8 Million
57       25.9 Million
58      107.6 Million
59       42.4 Million
60       21.5 Million
61         21 Million
62       44.6 Million
63        5.8 Million
64       89.7 Million
65       10.7 Million
66       12.8 Million
67          9 Million
68      146.3 Million
69       14.3 Million
70        6.2 Million
71        4.7 Million
72       20.9 Million
73        4.6 Million
74        6.7 Million
75         10 Million
76        8.2 Million
77        4.3 Million
78        7.2 Million
79        4.7 Million
80       16.3 Million
81       54.4 Million
82        5.1 Million
83       25.8 Million
84          9 Million
85          9 Million
86        4.5 Million
87      104.1 Million
88        3.9 Million
89       10.4 Million
90       14.4 Million
91        6.4 Million
92        4.9 Million
93        6.6 Million
94        7.3 Million
95        7.4 Million
96       15.3 Million
97       13.7 Million
98        4.8 Million
99       34.2 Million
100     102.9 Million
101      13.9 Million
102         9 Million
103        33 Million
104      14.4 Million
105      11.1 Million
106       3.5 Million
107       3.9 Million
108       7.6 Million
109      59.3 Million
110       4.7 Million
111       7.8 Million
112       3.8 Million
113       5.1 Million
114       6.4 Million
115        19 Million
116       3.3 Million
117       3.1 Million
118       3.7 Million
119      23.6 Million
120      25.8 Million
121      12.3 Million
122       6.6 Million
123        79 Million
124       3.5 Million
125      38.8 Million
126       4.7 Million
127       3.2 Million
128       3.2 Million
129        30 Million
130       3.1 Million
131       6.7 Million
132      84.8 Million
133      12.4 Million
134      38.8 Million
135         4 Million
136       5.4 Million
137       6.5 Million
138       9.8 Million
139      20.4 Million
140       3.1 Million
141       7.1 Million
142     101.1 Million
143      25.1 Million
144       4.7 Million
145       3.5 Million
146       5.4 Million
147       9.2 Million
148      18.5 Million
149       2.8 Million
150       5.5 Million
151       4.4 Million
152      21.8 Million
153       4.4 Million
154      28.4 Million
155         4 Million
156      13.6 Million
157         3 Million
158      20.6 Million
159         3 Million
160       4.9 Million
161      72.3 Million
162      13.3 Million
163       2.5 Million
164      15.9 Million
165     100.8 Million
166         3 Million
167      15.5 Million
168      53.1 Million
169       3.1 Million
170       6.4 Million
171         3 Million
172       5.7 Million
173      17.4 Million
174       2.6 Million
175      14.2 Million
176        12 Million
177       3.3 Million
178         7 Million
179       9.9 Million
180      10.3 Million
181       3.1 Million
182       4.6 Million
183      12.8 Million
184       2.7 Million
185      85.8 Million
186       5.4 Million
187       8.2 Million
188       6.9 Million
189       7.2 Million
190      12.7 Million
191       4.1 Million
192      24.7 Million
193       4.5 Million
194      32.9 Million
195       2.2 Million
196       3.6 Million
197      20.8 Million
198       3.6 Million
199      14.3 Million
200         4 Million
201     138.4 Million
202      40.5 Million
203       2.3 Million
204       2.2 Million
205      37.5 Million
206       5.1 Million
207     113.5 Million
208       3.9 Million
209      22.3 Million
210       3.6 Million
211       4.4 Million
212      61.1 Million
213       2.7 Million
214       4.1 Million
215     161.8 Million
216      31.5 Million
217       4.5 Million
218       3.5 Million
219      18.7 Million
220       6.1 Million
221        10 Million
222       2.7 Million
223       7.7 Million
224       4.5 Million
225       8.2 Million
226       6.6 Million
227      10.7 Million
228       7.2 Million
229       2.6 Million
230       2.9 Million
231      46.2 Million
232     120.5 Million
233       4.7 Million
234        12 Million
235       2.3 Million
236       4.3 Million
237      11.1 Million
238       3.6 Million
239       7.3 Million
240       6.3 Million
241       3.3 Million
242       2.1 Million
243       5.3 Million
244      26.3 Million
245       4.6 Million
246      13.4 Million
247     467.4 Million
248       8.3 Million
249       2.3 Million
250       4.4 Million
251      46.2 Million
252       7.4 Million
253       3.7 Million
254       3.1 Million
255      10.5 Million
256      10.1 Million
257       8.8 Million
258      58.8 Million
259       7.2 Million
260       3.7 Million
261       4.2 Million
262       8.5 Million
263       4.7 Million
264       4.5 Million
265       2.6 Million
266       2.2 Million
267      71.6 Million
268     726.1 Million
269       2.7 Million
270     259.4 Million
271       7.7 Million
272       8.6 Million
273        14 Million
274         3 Million
275      18.4 Million
276       4.1 Million
277       8.4 Million
278       5.5 Million
279       5.2 Million
280       3.4 Million
281       2.3 Million
282      40.9 Million
283      13.7 Million
284      93.9 Million
285       4.9 Million
286     113.5 Million
287       2.7 Million
288       9.1 Million
289      97.4 Million
290       2.6 Million
291       6.1 Million
292       9.8 Million
293      20.8 Million
294       3.6 Million
295       2.2 Million
296       6.3 Million
297       9.1 Million
298      11.8 Million
299       3.2 Million
300      14.1 Million
301       6.6 Million
302       2.7 Million
303      47.1 Million
304      65.2 Million
305       4.4 Million
306      76.9 Million
307      16.1 Million
308       6.8 Million
309       2.9 Million
310       3.4 Million
311       5.8 Million
312       3.2 Million
313       5.3 Million
314         2 Million
315      35.7 Million
316       9.9 Million
317       2.3 Million
318       5.8 Million
319       2.8 Million
320      25.1 Million
321     134.2 Million
322         5 Million
323       8.2 Million
324       2.6 Million
325       2.3 Million
326       3.8 Million
327       6.8 Million
328      27.3 Million
329       9.7 Million
330       2.9 Million
331      16.2 Million
332         2 Million
333       3.4 Million
334         4 Million
335       2.8 Million
336       2.2 Million
337       3.7 Million
338       5.7 Million
339         6 Million
340         2 Million
341       2.2 Million
342      12.4 Million
343       4.3 Million
344      33.8 Million
345       7.2 Million
346      64.3 Million
347       2.7 Million
348      29.1 Million
349      10.4 Million
350       2.3 Million
351      35.3 Million
352      24.2 Million
353       5.7 Million
354      19.7 Million
355       2.9 Million
356       2.3 Million
357         8 Million
358       8.1 Million
359       5.9 Million
360       2.1 Million
361       5.9 Million
362       8.8 Million
363        16 Million
364        12 Million
365      15.3 Million
366        28 Million
367       2.6 Million
368       2.6 Million
369       3.1 Million
370       4.7 Million
371       2.7 Million
372       6.4 Million
373      21.7 Million
374       3.4 Million
375         4 Million
376     137.2 Million
377       3.8 Million
378      31.4 Million
379         2 Million
380      21.6 Million
381         7 Million
382      30.8 Million
383     255.9 Million
384       6.2 Million
385      12.8 Million
386       5.1 Million
387      19.5 Million
388       2.5 Million
389       4.8 Million
390       2.9 Million
391       4.6 Million
392       2.8 Million
393       4.7 Million
394         2 Million
395       2.9 Million
396      10.1 Million
397       6.9 Million
398         3 Million
399       2.8 Million
400       5.4 Million
401      15.4 Million
402       9.5 Million
403       4.1 Million
404     211.2 Million
405        24 Million
406      32.7 Million
407       3.6 Million
408      21.5 Million
409       5.6 Million
410      11.6 Million
411       8.8 Million
412       7.1 Million
413     368.6 Million
414       5.5 Million
415       2.8 Million
416        14 Million
417       8.8 Million
418      15.8 Million
419      35.9 Million
420         7 Million
421       2.8 Million
422         2 Million
423       6.9 Million
424       9.8 Million
425       6.5 Million
426       5.4 Million
427     374.2 Million
428       5.9 Million
429       5.2 Million
430       4.3 Million
431       4.9 Million
432       8.6 Million
433      20.4 Million
434      13.2 Million
435      38.5 Million
436      21.3 Million
437      67.8 Million
438      10.1 Million
439      20.8 Million
440      94.6 Million
441       2.4 Million
442      15.9 Million
443      12.7 Million
444       8.9 Million
445       4.1 Million
446         3 Million
447      22.3 Million
448      31.4 Million
449      74.3 Million
450       3.9 Million
451       5.9 Million
452      45.1 Million
453       2.7 Million
454      18.6 Million
455     159.7 Million
456       4.4 Million
457      29.8 Million
458       3.6 Million
459      11.3 Million
460       7.8 Million
461       2.8 Million
462       3.2 Million
463      18.8 Million
464       7.5 Million
465      14.2 Million
466      17.4 Million
467       5.8 Million
468       4.5 Million
469      52.3 Million
470        40 Million
471      42.9 Million
472      11.6 Million
473         2 Million
474       7.1 Million
475         2 Million
476      30.1 Million
477         3 Million
478       7.7 Million
479      22.1 Million
480       2.5 Million
481       2.3 Million
482       2.5 Million
483      31.3 Million
484       3.5 Million
485       7.2 Million
486      59.4 Million
487      78.6 Million
488      11.4 Million
489       5.4 Million
490      45.4 Million
491      52.4 Million
492       5.4 Million
493       5.3 Million
494      18.4 Million
495       2.2 Million
496       2.9 Million
497      21.3 Million
498       5.1 Million
499       4.9 Million
500         8 Million
501      12.3 Million
502       4.7 Million
503       3.5 Million
504       8.5 Million
505      18.1 Million
506         9 Million
507      10.7 Million
508      84.3 Million
509      10.3 Million
510       2.1 Million
511      16.2 Million
512      27.2 Million
513       2.2 Million
514       2.4 Million
515       8.7 Million
516       6.1 Million
517      16.3 Million
518       3.8 Million
519      12.6 Million
520       9.7 Million
521      21.3 Million
522       6.6 Million
523       2.5 Million
524      17.5 Million
525     492.5 Million
526         6 Million
527       4.5 Million
528       9.5 Million
529       4.8 Million
530         3 Million
531       2.2 Million
532       4.5 Million
533      15.3 Million
534       2.9 Million
535       7.9 Million
536      53.5 Million
537      13.6 Million
538        19 Million
539       4.7 Million
540       2.4 Million
541       8.1 Million
542         2 Million
543     171.8 Million
544      31.6 Million
545       8.2 Million
546       7.3 Million
547       6.2 Million
548      10.7 Million
549       5.5 Million
550      37.6 Million
551       7.5 Million
552        11 Million
553       5.3 Million
554         6 Million
555      10.7 Million
556       9.2 Million
557       2.2 Million
558      12.6 Million
559      27.4 Million
560         2 Million
561      17.2 Million
562     138.5 Million
563       6.9 Million
564      77.4 Million
565      16.7 Million
566       8.9 Million
567       2.8 Million
568      70.7 Million
569      46.4 Million
570         5 Million
571       3.7 Million
572      17.5 Million
573      41.9 Million
574      79.6 Million
575      16.4 Million
576      12.5 Million
577      37.3 Million
578       4.6 Million
579         7 Million
580        10 Million
581       6.1 Million
582      17.1 Million
583      45.5 Million
584      21.8 Million
585       3.6 Million
586       2.5 Million
587      18.8 Million
588       3.7 Million
589       4.1 Million
590       3.4 Million
591        13 Million
592      16.9 Million
593         6 Million
594         5 Million
595       5.3 Million
596         2 Million
597      14.9 Million
598         4 Million
599        44 Million
600         6 Million
601       3.4 Million
602       2.4 Million
603      10.9 Million
604      14.8 Million
605       3.5 Billion
606         6 Million
607       3.5 Million
608       2.9 Million
609       6.3 Million
610       2.9 Million
611       9.2 Million
612       5.8 Million
613       2.2 Million
614      15.6 Million
615      27.6 Million
616      36.5 Million
617       2.9 Million
618       5.9 Million
619      29.7 Million
620      29.6 Million
621      22.9 Million
622      73.3 Million
623      10.3 Million
624       7.2 Million
625       5.5 Million
626       5.7 Million
627       7.3 Million
628      75.3 Million
629       3.1 Million
630       2.7 Million
631      49.1 Million
632         9 Million
633       6.4 Million
634       6.4 Million
635       2.2 Million
636       9.5 Million
637      78.5 Million
638       2.3 Million
639         2 Million
640      22.8 Million
641      39.4 Million
642      13.6 Million
643      13.4 Million
644         8 Million
645       2.6 Million
646       5.5 Million
647       2.4 Million
648       4.1 Million
649       5.5 Million
650         4 Million
651       2.9 Million
652      22.3 Million
653        70 Million
654      93.2 Million
655      27.2 Million
656     273.7 Million
657      31.5 Million
658       2.2 Million
659        62 Million
660       2.5 Million
661      12.1 Million
662      33.6 Million
663      37.1 Million
664         5 Million
665      17.6 Million
666      88.3 Million
667       2.1 Million
668       2.7 Million
669       6.6 Million
670      13.2 Million
671       2.6 Million
672      14.1 Million
673       5.2 Million
674       2.3 Million
675       2.1 Million
676       5.2 Million
677       6.3 Million
678       2.5 Million
679      14.9 Million
680       8.9 Million
681       4.2 Million
682      17.3 Million
683      49.4 Million
684       5.6 Million
685      14.2 Million
686       8.3 Million
687         3 Million
688      13.7 Million
689      12.4 Million
690       4.9 Million
691       4.2 Million
692       6.6 Million
693       9.2 Million
694       7.7 Million
695       4.8 Million
696       2.2 Million
697       9.9 Million
698      13.9 Million
699     157.1 Million
700       2.9 Million
701      18.5 Million
702      12.1 Million
703      16.7 Million
704         2 Million
705      23.6 Million
706     151.5 Million
707       9.6 Million
708      11.3 Million
709         9 Million
710       5.5 Million
711      18.6 Million
712         6 Million
713     101.3 Million
714      30.8 Million
715       2.2 Million
716       3.6 Million
717       4.6 Million
718       4.1 Million
719       8.8 Million
720       5.5 Million
721      18.3 Million
722       8.6 Million
723       3.8 Million
724      12.4 Million
725       9.8 Million
726      33.1 Million
727       2.9 Million
728       3.5 Million
729      66.6 Million
730      92.7 Million
731      23.7 Million
732         2 Million
733      14.4 Million
734      32.6 Million
735      73.2 Million
736       2.2 Million
737       2.3 Million
738      30.2 Million
739      12.9 Million
740       3.9 Million
741       2.5 Million
742       6.9 Million
743      11.1 Million
744       4.5 Million
745      48.7 Million
746       6.1 Million
747       4.2 Million
748       2.2 Million
749      17.8 Million
750       2.8 Million
751       4.1 Million
752     225.8 Million
753       5.7 Million
754      15.2 Million
755       2.3 Million
756      11.4 Million
757      28.6 Million
758     129.6 Million
759       9.3 Million
760      75.5 Million
761      23.7 Million
762         5 Million
763       5.7 Million
764       3.4 Million
765       2.2 Million
766      40.9 Million
767       4.8 Million
768      19.4 Million
769      13.8 Million
770      39.3 Million
771      10.9 Million
772       3.5 Million
773       8.1 Million
774       4.6 Million
775       2.6 Million
776      14.6 Million
777       7.2 Million
778       5.1 Million
779       5.6 Million
780         5 Million
781      25.4 Million
782         4 Million
783     172.5 Million
784      14.3 Million
785      22.5 Million
786      14.8 Million
787     114.5 Million
788       2.3 Million
789      16.2 Million
790       6.3 Million
791       5.7 Million
792      44.2 Million
793       2.3 Million
794        11 Million
795       7.3 Million
796      11.3 Million
797       8.4 Million
798       2.2 Million
799       6.3 Million
800       3.5 Million
801       3.2 Million
802      18.4 Million
803         3 Million
804      35.6 Million
805       5.7 Million
806       5.8 Million
807       6.5 Million
808       4.3 Million
809       6.4 Million
810      23.6 Million
811       2.7 Million
812     146.8 Million
813       7.2 Million
814      84.7 Million
815         7 Million
816        75 Million
817      18.1 Million
818       3.1 Million
819       9.2 Million
820       2.4 Million
821       2.7 Million
822       8.2 Million
823      19.5 Million
824       4.5 Million
825       3.7 Million
826         4 Million
827       3.4 Million
828       8.8 Million
829      24.3 Million
830       4.2 Million
831       4.5 Million
832      21.7 Million
833       5.1 Million
834       4.8 Million
835       5.1 Million
836      12.2 Million
837       9.3 Million
838     102.2 Million
839       9.5 Million
840       3.1 Million
841       5.5 Million
842       5.8 Million
843       2.9 Million
844      11.1 Million
845         3 Million
846      11.6 Million
847      72.8 Million
848       4.9 Million
849      69.7 Million
850         7 Million
851       3.5 Million
852       4.1 Million
853       5.4 Million
854      14.6 Million
855      14.4 Million
856      44.8 Million
857        20 Million
858      14.5 Million
859       6.5 Million
860       2.9 Million
861      59.9 Million
862       5.6 Million
863      21.4 Million
864        27 Million
865       7.5 Million
866        13 Million
867        14 Million
868      17.2 Million
869      32.6 Million
870     105.6 Million
871       3.2 Million
872      11.2 Million
873      13.1 Million
874       5.2 Million
875       5.4 Million
876       2.7 Million
877       2.7 Million
878       7.6 Million
879      39.8 Million
880      12.1 Million
881      46.3 Million
882      56.4 Million
883      10.2 Million
884      24.2 Million
885       4.1 Million
886       2.7 Million
887        16 Million
888      21.3 Million
889       4.7 Million
890      26.6 Million
891       2.1 Million
892       2.5 Million
893        14 Million
894      31.1 Million
895       4.2 Million
896       3.7 Million
897       3.5 Million
898      15.7 Million
899      99.6 Million
900       4.7 Million
901       5.1 Million
902       2.4 Million
903      16.4 Million
904       2.8 Million
905       2.8 Million
906       8.6 Million
907      29.6 Million
908       4.6 Million

In [41]:
df['revenue'] = df['revenue'].replace({'Million':'', 'Billion': '*1000'}, regex = True).map(pd.eval)

In [42]:
df

,rank,profile,name,url,state,revenue,growth_%,industry,workers,previous_workers,founded,yrs_on_list,metro,city
0,1,https://www.inc.com/profile/freestar,Freestar,http://freestar.com,AZ,36.9,36680.3882,Advertising & Marketing,40.0,5,2015,1,Phoenix,Phoenix
1,2,https://www.inc.com/profile/freightwise,FreightWise,http://freightwisellc.com,TN,33.6,30547.9317,Logistics & Transportation,39.0,8,2015,1,Nashville,Brentwood
2,3,https://www.inc.com/profile/ceces-veggie,Cece's Veggie Co.,http://cecesveggieco.com,TX,24.9,23880.4852,Food & Beverage,190.0,10,2015,1,Austin,Austin
3,4,https://www.inc.com/profile/ladyboss,LadyBoss,http://ladyboss.com,NM,32.4,21849.8925,Consumer Products & Services,57.0,2,2014,1,NaN,Albuquerque
4,5,https://www.inc.com/profile/perpay,Perpay,http://perpay.com,PA,22.5,18166.4070,Retail,25.0,6,2014,1,Philadelphia,Philadelphia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5007,4996,https://www.inc.com/profile/village-plumbing-air,Village Plumbing & Air,villageplumbing.com,TX,15.8,52.2377,Consumer Products & Services,88.0,62,1946,3,Houston,Houston
5008,4997,https://www.inc.com/profile/real-restoration-g...,Real Restoration Group,realrestoration.com,IL,11.6,52.2127,Construction,380.0,220,2011,1,Chicago,Chicago
5009,4998,https://www.inc.com/profile/naval-systems,Naval Systems,n-s-i.us,MD,29.7,52.2037,Government Services,187.0,127,2004,1,NaN,LEXINGTON PARK
5010,4999,https://www.inc.com/profile/hnm-systems,HNM Systems,hnmsystems.com,CA,8.8,52.1919,Telecommunications,132.0,47,2011,1,San Diego,Solana Beach
5011,5000,https://www.inc.com/profile/vivayic,Vivayic,vivayic.com,NE,4.5,52.1691,Business Products & Services,27.0,22,2006,4,NaN,Lincoln

In [43]:
for i in df.columns:
    print('column:' + i + ', ' + 'nans: ' +  str(df[i].isna().sum()))

column:rank, nans: 0
column:profile, nans: 0
column:name, nans: 0
column:url, nans: 0
column:state, nans: 0
column:revenue, nans: 0
column:growth_%, nans: 0
column:industry, nans: 0
column:workers, nans: 1
column:previous_workers, nans: 0
column:founded, nans: 0
column:yrs_on_list, nans: 0
column:metro, nans: 813
column:city, nans: 0

In [44]:
df['workers'].fillna(df['workers'].median(), inplace=True)

In [45]:
metro_mode = df['metro'].mode()[0]

In [46]:
df['metro'].fillna(metro_mode, inplace = True)

In [47]:
df = df.drop(columns=['profile', 'url'])

In [50]:
df

,rank,name,state,revenue,growth_%,industry,workers,previous_workers,founded,yrs_on_list,metro,city
0,1,Freestar,AZ,36.9,36680.3882,Advertising & Marketing,40.0,5,2015,1,Phoenix,Phoenix
1,2,FreightWise,TN,33.6,30547.9317,Logistics & Transportation,39.0,8,2015,1,Nashville,Brentwood
2,3,Cece's Veggie Co.,TX,24.9,23880.4852,Food & Beverage,190.0,10,2015,1,Austin,Austin
3,4,LadyBoss,NM,32.4,21849.8925,Consumer Products & Services,57.0,2,2014,1,New York City,Albuquerque
4,5,Perpay,PA,22.5,18166.4070,Retail,25.0,6,2014,1,Philadelphia,Philadelphia
...,...,...,...,...,...,...,...,...,...,...,...,...
5007,4996,Village Plumbing & Air,TX,15.8,52.2377,Consumer Products & Services,88.0,62,1946,3,Houston,Houston
5008,4997,Real Restoration Group,IL,11.6,52.2127,Construction,380.0,220,2011,1,Chicago,Chicago
5009,4998,Naval Systems,MD,29.7,52.2037,Government Services,187.0,127,2004,1,New York City,LEXINGTON PARK
5010,4999,HNM Systems,CA,8.8,52.1919,Telecommunications,132.0,47,2011,1,San Diego,Solana Beach
5011,5000,Vivayic,NE,4.5,52.1691,Business Products & Services,27.0,22,2006,4,New York City,Lincoln

In [51]:
curr_df = df[(df['metro'] == 'San Diego') & (df['state'] == 'CA')]['city'].unique()
curr_df

array(['Oceanside', 'San Diego', 'Solana Beach', 'Poway', 'La Jolla',
       'Solana Bech', 'Rancho Santa Fe', 'Carlsbad', 'San Marcos',
       'Buellton', 'Encinitas', 'Escondido', 'Vista', 'Jamul', 'El Cajon',
       'Santee', 'Del Mar', 'Chula Vista', 'Encinitass'], dtype=object)

In [52]:
df_cities = pd.read_csv('data.csv')

In [53]:
to_merge = df_cities[['city','latitude', 'longitude']]
to_merge['city'].unique()

array(['San Diego', 'Oceanside', 'Alpine', 'Escondido', 'San Marcos',
       'Vista', 'San Ysidro', 'Chula Vista', 'Rancho San Diego',
       'Casa de Oro-Mount Helix', 'Ramona', 'Fallbrook', 'Winter Gardens',
       'Lemon Grove', 'El Cajon', 'Encinitas', 'Camp Pendleton',
       'Bonsall', 'Coronado', 'Del Mar', 'La Mesa', 'National City',
       'Imperial Beach', 'La Presa', 'Santee', 'Poway', 'Lakeside',
       'Carlsbad', 'Camp Pendleton South'], dtype=object)

In [54]:
for i in curr_df:
    print('city: ' + i + ' ' + str(i in to_merge['city'].unique()))

city: Oceanside True
city: San Diego True
city: Solana Beach False
city: Poway True
city: La Jolla False
city: Solana Bech False
city: Rancho Santa Fe False
city: Carlsbad True
city: San Marcos True
city: Buellton False
city: Encinitas True
city: Escondido True
city: Vista True
city: Jamul False
city: El Cajon True
city: Santee True
city: Del Mar True
city: Chula Vista True
city: Encinitass False

In [55]:
filter_out = []
for i in curr_df:
    if str(i in to_merge['city'].unique()) == 'False':
        filter_out.append(i)
filter_out

['Solana Beach',
 'La Jolla',
 'Solana Bech',
 'Rancho Santa Fe',
 'Buellton',
 'Jamul',
 'Encinitass']

In [56]:
df['city'] = df['city'].replace({'Encinitass':'Encinitas', 'Solana Bech': 'Solana Beach'}, regex = True)

In [57]:
filter_out = []
for i in df[df['metro'] == 'San Diego']['city'].unique():
    if str(i in to_merge['city'].unique()) == 'False':
        filter_out.append(i)
filter_out

['Solana Beach',
 'La Jolla',
 'Rancho Santa Fe',
 'Buellton',
 'Jamul',
 'Alpharetta']

In [58]:
d = {'city': ['Solana Beach', 'La Jolla', 'Rancho Santa Fe', 'Jamul'], 'latitude': [32.9912, 32.842674, 33.0203, 32.7170], 'longitude': [-117.2711, -117.2713, -117.2028, -116.8761]}
other_cities = pd.DataFrame(d)

In [59]:
to_merge = to_merge.drop_duplicates(subset = ['city']).reset_index(drop = True)
to_merge = pd.concat([to_merge, other_cities]).reset_index(drop = True)
to_merge = to_merge.drop_duplicates(subset = ['city']).reset_index(drop = True)
to_merge

                       city   latitude   longitude
0                 San Diego  32.832268 -117.165349
1                 Oceanside  33.224648 -117.332919
2                    Alpine  32.834181 -116.750238
3                 Escondido  33.147542 -117.105994
4                San Marcos  33.139005 -117.174056
5                     Vista  33.199934 -117.246469
6                San Ysidro  32.557531 -117.058314
7               Chula Vista  32.614709 -117.025407
8          Rancho San Diego  32.739979 -116.942189
9   Casa de Oro-Mount Helix  32.747502 -116.961275
10                   Ramona  33.036348 -116.878161
11                Fallbrook  33.371484 -117.252088
12           Winter Gardens  32.852878 -116.931490
13              Lemon Grove  32.742728 -117.047905
14                 El Cajon  32.811479 -116.918434
15                Encinitas  33.049446 -117.260575
16           Camp Pendleton  33.296683 -117.350985
17                  Bonsall  33.289749 -117.226500
18                 Coronado  32.697832 -117.204362
19                  Del Mar  32.980284 -117.249522
20                  La Mesa  32.773831 -117.026222
21            National City  32.677669 -117.098219
22           Imperial Beach  32.584254 -117.108391
23                 La Presa  32.706968 -117.009005
24                   Santee  32.837871 -116.984129
25                    Poway  32.952697 -117.059712
26                 Lakeside  32.862077 -116.922615
27                 Carlsbad  33.122583 -117.324243
28     Camp Pendleton South  33.225199 -117.392285
29             Solana Beach  32.991200 -117.271100
30                 La Jolla  32.842674 -117.271300
31          Rancho Santa Fe  33.020300 -117.202800
32                    Jamul  32.717000 -116.876100

In [60]:
new = pd.merge(df, to_merge, on = 'city', how = 'left')

In [61]:
new[new['metro'] == 'San Diego']

,rank,name,state,revenue,growth_%,industry,workers,previous_workers,founded,yrs_on_list,metro,city,latitude,longitude
19,20,Kindred Bravely,CA,9.6,8543.9808,Consumer Products & Services,35.0,2,2015,1,San Diego,Oceanside,33.224648,-117.332919
96,96,Amenity Health,CA,15.3,3357.7038,Health,16.0,8,2011,1,San Diego,San Diego,32.832268,-117.165349
112,112,Cience Technologies,CA,3.8,3050.0025,Advertising & Marketing,310.0,30,2015,1,San Diego,Solana Beach,32.991200,-117.271100
178,178,Tricopian,CA,7.0,2171.9647,Consumer Products & Services,18.0,5,2011,1,San Diego,Poway,32.952697,-117.059712
236,236,Gateway Genomics,CA,4.3,1786.4145,Health,19.0,10,2014,1,San Diego,La Jolla,32.842674,-117.271300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4903,4892,Environmental Lights,CA,27.1,55.5905,Business Products & Services,54.0,32,2006,7,San Diego,San Diego,32.832268,-117.165349
4986,4975,The Perfect Workout,CA,18.0,52.8711,Health,285.0,200,1999,1,San Diego,Encinitas,33.049446,-117.260575
4990,4979,Jackson Design and Remodeling,CA,21.3,52.7881,Construction,62.0,48,1989,10,San Diego,San Diego,32.832268,-117.165349
5000,4989,Taco Truck Creative,CA,3.6,52.5410,Advertising & Marketing,14.0,6,2013,1,San Diego,Carlsbad,33.122583,-117.324243
5010,4999,HNM Systems,CA,8.8,52.1919,Telecommunications,132.0,47,2011,1,San Diego,Solana Beach,32.991200,-117.271100

In [64]:
new

,rank,name,state,revenue,growth_%,industry,workers,previous_workers,founded,yrs_on_list,metro,city,latitude,longitude
0,1,Freestar,AZ,36.9,36680.3882,Advertising & Marketing,40.0,5,2015,1,Phoenix,Phoenix,NaN,NaN
1,2,FreightWise,TN,33.6,30547.9317,Logistics & Transportation,39.0,8,2015,1,Nashville,Brentwood,NaN,NaN
2,3,Cece's Veggie Co.,TX,24.9,23880.4852,Food & Beverage,190.0,10,2015,1,Austin,Austin,NaN,NaN
3,4,LadyBoss,NM,32.4,21849.8925,Consumer Products & Services,57.0,2,2014,1,New York City,Albuquerque,NaN,NaN
4,5,Perpay,PA,22.5,18166.4070,Retail,25.0,6,2014,1,Philadelphia,Philadelphia,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5007,4996,Village Plumbing & Air,TX,15.8,52.2377,Consumer Products & Services,88.0,62,1946,3,Houston,Houston,NaN,NaN
5008,4997,Real Restoration Group,IL,11.6,52.2127,Construction,380.0,220,2011,1,Chicago,Chicago,NaN,NaN
5009,4998,Naval Systems,MD,29.7,52.2037,Government Services,187.0,127,2004,1,New York City,LEXINGTON PARK,NaN,NaN
5010,4999,HNM Systems,CA,8.8,52.1919,Telecommunications,132.0,47,2011,1,San Diego,Solana Beach,32.9912,-117.2711
5011,5000,Vivayic,NE,4.5,52.1691,Business Products & Services,27.0,22,2006,4,New York City,Lincoln,NaN,NaN

In [65]:
new[(new['city'] == 'Alpharetta') & (new['metro'] == 'San Diego')]

,rank,name,state,revenue,growth_%,industry,workers,previous_workers,founded,yrs_on_list,metro,city,latitude,longitude
3814,3805,Automated Systems Design,GA,42.9,88.0387,IT Management,75.0,40,1987,6,San Diego,Alpharetta,NaN,NaN

In [66]:
new = new.drop(3814).reset_index(drop = True)

In [67]:
new[(new['city'] == 'Buellton') & (new['metro'] == 'San Diego')]

,rank,name,state,revenue,growth_%,industry,workers,previous_workers,founded,yrs_on_list,metro,city,latitude,longitude
1641,1637,Big Hammer Wines,CA,2.1,251.9223,Food & Beverage,1.0,1,2009,2,San Diego,Buellton,NaN,NaN

In [68]:
new = new.drop(1641).reset_index(drop = True)

In [69]:
new

,rank,name,state,revenue,growth_%,industry,workers,previous_workers,founded,yrs_on_list,metro,city,latitude,longitude
0,1,Freestar,AZ,36.9,36680.3882,Advertising & Marketing,40.0,5,2015,1,Phoenix,Phoenix,NaN,NaN
1,2,FreightWise,TN,33.6,30547.9317,Logistics & Transportation,39.0,8,2015,1,Nashville,Brentwood,NaN,NaN
2,3,Cece's Veggie Co.,TX,24.9,23880.4852,Food & Beverage,190.0,10,2015,1,Austin,Austin,NaN,NaN
3,4,LadyBoss,NM,32.4,21849.8925,Consumer Products & Services,57.0,2,2014,1,New York City,Albuquerque,NaN,NaN
4,5,Perpay,PA,22.5,18166.4070,Retail,25.0,6,2014,1,Philadelphia,Philadelphia,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5005,4996,Village Plumbing & Air,TX,15.8,52.2377,Consumer Products & Services,88.0,62,1946,3,Houston,Houston,NaN,NaN
5006,4997,Real Restoration Group,IL,11.6,52.2127,Construction,380.0,220,2011,1,Chicago,Chicago,NaN,NaN
5007,4998,Naval Systems,MD,29.7,52.2037,Government Services,187.0,127,2004,1,New York City,LEXINGTON PARK,NaN,NaN
5008,4999,HNM Systems,CA,8.8,52.1919,Telecommunications,132.0,47,2011,1,San Diego,Solana Beach,32.9912,-117.2711
5009,5000,Vivayic,NE,4.5,52.1691,Business Products & Services,27.0,22,2006,4,New York City,Lincoln,NaN,NaN

In [71]:
new.to_csv('data1.csv')